FROM node:20

WORKDIR /app/frontend

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
# Generate Database
RUN npm run db:generate

# Building app
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start-frontend-app"]