FROM node:20

WORKDIR /app/chatapp

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
# Generate database
RUN npm run db:generate

# Building app
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start-chatapp-app"]